# validatingwebhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: my-mutating-webhook
webhooks:
  - name: webhook.default.svc.cluster.local
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRHRKeXBrK0JyTy9UQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05Nakl3TXpFNU1EWXhNVFExV2hnUE1qSTVOakF4TURJd05qRXhORFZhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1BSEZPemZFVUoxbTJLelpiV2FrS0tJWWNqdEVVU2NHUVhkbFFPaXFndXN5SnB6RjVGdW1NNE0KdjNHVnZ2Y2dJcDMzWTd2YjBJZlh1Q1l4Wkt6Z015WmEvUG93dVVpZDk3b3RzWDRVVHNuWkdwT0ZhaUtlTldEYQo4L0t4RFpHZnBrNVkyYTg0b3hBUEJXZXJsZzVHSGtsUkxiOEhmbzE2Z1h1dGJYRFJ2WGtqNWQ5QTBIejZsOUdXCkFJY2xLUkNtbmNReHZ5Y29RQ1pqSHVLWU04eFllM0NpYUVBUUlBc2cyNEVVUEsxdXhQZ3NtL3RkMjVIa294bzIKWGh1TzVHMGwxYXB6MkFDMUwrUGtPaFNrcHA0ZGs2SHNjOFdYb0RrbVdVVHhnZUQ2dmtZd0tTVElBSGx4RUZrVApKZEJpQkJRa2FBTlllNE9UWW9BRU5ZcXdWMzdTNDgwQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmdnOFdzU29QMS9tanVVVWFaQlNSdlVyRnlVdkg2eUxMVWhhbTA2Nko1OTNhcU9yQUgrTnptUEl4Snl1MmQ2cXkKdnAxV3BlSjdqYXNlOWoxQXdMZStSMklyYUVmcXZBK2ZBVHJna1dYQnJlYzl4U2dQS3U5V2VnRFdTQVhURFRvRgpGKzl4czYxVitMRitVQSsweEhQdFkxWWlHZWt6WWZRVWxNTHBEWXdpUFJWakV1TzFFTUdGMG43Z244ODN2anNVCmZtRXhRdUlnT292WmhlRXBRRkx1TFZkQllnYkMrVitiQzdSM1pOT2xvbWR0VWMrZGRheDY3RkRTb3BubkVLRkwKdDNPM0h6TVZUbFNHcEFsWitoT0VwR1kwZ3daTzFPR2szT2ZpLzYvV1JhRXh6UkdGdm9BRGF2MkhQSXhUZERqNApqeUIrcHJyMlBiVmZHcnFYYkE1aDVnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: default
        name: webhook
        path: "/test"
