
# 웹훅으로 보내야 하는 리소스 요청을 k8에 알려주는 역할
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-mutating
webhooks:
  - name: webhook.default.svc.cluster.local
    clientConfig: # admission controller server에 대한 구성
      service: ### admission Review요청을 보낼 서비스
        name: webhook # admission controller server 의 서비스명
        namespace: default # 내 admission controller server 가 어디있는지
        path: "/test" # admission controller가 이 웹훅 요청을 수신할 경로
      caBundle: $(cat ca.crt | base64 | tr -d '\n')
    rules: # Pod생성시에 이 작업을 수행하겠다.
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    #failurePolicy: Ignore